// <auto-generated />
using System;
using ArgusCloud.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArgusCloud.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Argus.Agent.Maquina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("LocalizacaoMaquina")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SistemaOperacional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("ArgusCloud.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ExporProcessos")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("MaquinaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PermiteEspelharemProcessos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TokenAgenteHash")
                        .HasColumnType("longtext");

                    b.Property<string>("TokenTemporarioAgente")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ArgusCloud.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Argus.Agent.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId");

                    b.Navigation("Maquina");
                });
#pragma warning restore 612, 618
        }
    }
}
