export default [
  {
    id: 58464,
    nome: 'Argus.Agent (Running) - Worker.cs - Microsoft Visual Studio',
    nomeExecutavel:
      '"C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe"',
    memoriaUsoMB: 1179,
    memoriaVirtualUsoMB: 2139240,
    numeroThreads: 125,
    usoCpuModoUsuario: 0.12,
    usoCpuModoPrivilegiado: 0.42,
    usoCpuTotal: 0.54,
  },
  {
    id: 68588,
    nome: 'Spotify',
    nomeExecutavel:
      'C:\\Program Files\\WindowsApps\\SpotifyAB.SpotifyMusic_1.271.421.0_x64__zpdnekdrzrea0\\Spotify.exe',
    memoriaUsoMB: 305,
    memoriaVirtualUsoMB: 3589954,
    numeroThreads: 31,
    usoCpuModoUsuario: 0.02,
    usoCpuModoPrivilegiado: 0.24,
    usoCpuTotal: 0.26,
  },
  {
    id: 76508,
    nome: 'Visual Studio Code',
    nomeExecutavel: 'C:\\Users\\thiag\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
    memoriaUsoMB: 306,
    memoriaVirtualUsoMB: 3527771,
    numeroThreads: 28,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 87940,
    nome: 'Justin Bieber - NEED IT',
    nomeExecutavel:
      'C:\\Program Files\\WindowsApps\\SpotifyAB.SpotifyMusic_1.271.421.0_x64__zpdnekdrzrea0\\Spotify.exe',
    memoriaUsoMB: 149,
    memoriaVirtualUsoMB: 2200594,
    numeroThreads: 119,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0.06,
    usoCpuTotal: 0.06,
  },
  {
    id: 45664,
    nome: 'ArgusCloud (Running) - MonitoramentoHub.cs - Microsoft Visual Studio',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe',
    memoriaUsoMB: 809,
    memoriaVirtualUsoMB: 2139334,
    numeroThreads: 94,
    usoCpuModoUsuario: 0.08,
    usoCpuModoPrivilegiado: 0.28,
    usoCpuTotal: 0.36,
  },
  {
    id: 81636,
    nome: 'Visual Studio Code',
    nomeExecutavel: 'C:\\Users\\thiag\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
    memoriaUsoMB: 627,
    memoriaVirtualUsoMB: 3524332,
    numeroThreads: 21,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 75144,
    nome: 'ServiceHub.IntellicodeModelService.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.netfx.x64\\ServiceHub.IntellicodeModelService.exe',
    memoriaUsoMB: 490,
    memoriaVirtualUsoMB: 5539,
    numeroThreads: 38,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 78292,
    nome: 'Visual Studio Code',
    nomeExecutavel: 'C:\\Users\\thiag\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
    memoriaUsoMB: 415,
    memoriaVirtualUsoMB: 3525936,
    numeroThreads: 15,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 68728,
    nome: 'ServiceHub.RoslynCodeAnalysisService.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.RoslynCodeAnalysisService.exe',
    memoriaUsoMB: 313,
    memoriaVirtualUsoMB: 2366347,
    numeroThreads: 32,
    usoCpuModoUsuario: 0.04,
    usoCpuModoPrivilegiado: 0.02,
    usoCpuTotal: 0.06,
  },
  {
    id: 57556,
    nome: 'ServiceHub.Host.dotnet.x64',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.Host.dotnet.x64.exe',
    memoriaUsoMB: 223,
    memoriaVirtualUsoMB: 2366245,
    numeroThreads: 21,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 82148,
    nome: 'Microsoft Edge',
    nomeExecutavel: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    memoriaUsoMB: 210,
    memoriaVirtualUsoMB: 3588421,
    numeroThreads: 28,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 74064,
    nome: 'Google Gemini e mais 1 página - Pessoal — Microsoft​ Edge',
    nomeExecutavel: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    memoriaUsoMB: 186,
    memoriaVirtualUsoMB: 2266970,
    numeroThreads: 54,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 83756,
    nome: 'Spotify',
    nomeExecutavel:
      'C:\\Program Files\\WindowsApps\\SpotifyAB.SpotifyMusic_1.271.421.0_x64__zpdnekdrzrea0\\Spotify.exe',
    memoriaUsoMB: 176,
    memoriaVirtualUsoMB: 2200631,
    numeroThreads: 21,
    usoCpuModoUsuario: 0.08,
    usoCpuModoPrivilegiado: 0.2,
    usoCpuTotal: 0.28,
  },
  {
    id: 86172,
    nome: 'Microsoft Edge WebView2',
    nomeExecutavel:
      'C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\139.0.3405.125\\msedgewebview2.exe',
    memoriaUsoMB: 171,
    memoriaVirtualUsoMB: 3588372,
    numeroThreads: 26,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0.12,
    usoCpuTotal: 0.12,
  },
  {
    id: 76544,
    nome: 'ServiceHub.RoslynCodeAnalysisService.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.RoslynCodeAnalysisService.exe',
    memoriaUsoMB: 162,
    memoriaVirtualUsoMB: 2366351,
    numeroThreads: 18,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 24872,
    nome: 'Microsoft Edge',
    nomeExecutavel: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    memoriaUsoMB: 151,
    memoriaVirtualUsoMB: 2201255,
    numeroThreads: 28,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 81840,
    nome: 'VBCSCompiler',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\Roslyn\\VBCSCompiler.exe',
    memoriaUsoMB: 148,
    memoriaVirtualUsoMB: 25065,
    numeroThreads: 23,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 47084,
    nome: 'ArgusCloud.API',
    nomeExecutavel:
      'C:\\Users\\thiag\\Documents\\projetosPessoais\\ArgusGeral\\Argus\\backend\\ArgusCloud\\ArgusCloud.API\\bin\\Debug\\net9.0\\ArgusCloud.API.exe',
    memoriaUsoMB: 141,
    memoriaVirtualUsoMB: 2366180,
    numeroThreads: 40,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0.02,
    usoCpuTotal: 0.02,
  },
  {
    id: 78480,
    nome: 'dados - trabalhoGrande - Thiago PY - Visual Studio Code',
    nomeExecutavel: 'C:\\Users\\thiag\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
    memoriaUsoMB: 140,
    memoriaVirtualUsoMB: 3524678,
    numeroThreads: 49,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    id: 83092,
    nome: 'Microsoft Edge',
    nomeExecutavel: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    memoriaUsoMB: 137,
    memoriaVirtualUsoMB: 3590049,
    numeroThreads: 29,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
]
