export default [
  {
    subProcessos: [
      {
        id: 65376,
        nome: 'Argus.Agent (Running) - ProcessoInfo.cs - Microsoft Visual Studio',
        nomeExecutavel:
          'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe',
        memoriaUsoMB: 1239,
        memoriaVirtualUsoMB: 2139460,
        numeroThreads: 185,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 90528,
    nome: 'ArgusCloud (Running) - Maquina.cs - Microsoft Visual Studio',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\devenv.exe',
    memoriaUsoMB: 1290,
    memoriaVirtualUsoMB: 2139498,
    numeroThreads: 167,
    usoCpuModoUsuario: 0.11,
    usoCpuModoPrivilegiado: 0.22,
    usoCpuTotal: 0.32,
  },
  {
    subProcessos: [
      {
        id: 93872,
        nome: 'Node.js JavaScript Runtime',
        nomeExecutavel:
          'c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\extensions\\microsoft\\copilot\\service\\dist\\copilot-language-server.exe',
        memoriaUsoMB: 474,
        memoriaVirtualUsoMB: 36624,
        numeroThreads: 15,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 93544,
    nome: 'Node.js JavaScript Runtime',
    nomeExecutavel:
      'c:\\program files\\microsoft visual studio\\2022\\community\\common7\\ide\\extensions\\microsoft\\copilot\\service\\dist\\copilot-language-server.exe',
    memoriaUsoMB: 481,
    memoriaVirtualUsoMB: 36624,
    numeroThreads: 15,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [
      {
        id: 87824,
        nome: 'ServiceHub.RoslynCodeAnalysisService.exe',
        nomeExecutavel:
          'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.RoslynCodeAnalysisService.exe',
        memoriaUsoMB: 259,
        memoriaVirtualUsoMB: 2366328,
        numeroThreads: 35,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 71532,
    nome: 'ServiceHub.RoslynCodeAnalysisService.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.RoslynCodeAnalysisService.exe',
    memoriaUsoMB: 295,
    memoriaVirtualUsoMB: 2366347,
    numeroThreads: 31,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [
      {
        id: 92504,
        nome: 'ServiceHub.IntellicodeModelService.exe',
        nomeExecutavel:
          'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.netfx.x64\\ServiceHub.IntellicodeModelService.exe',
        memoriaUsoMB: 182,
        memoriaVirtualUsoMB: 5024,
        numeroThreads: 31,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 92376,
    nome: 'ServiceHub.IntellicodeModelService.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.netfx.x64\\ServiceHub.IntellicodeModelService.exe',
    memoriaUsoMB: 253,
    memoriaVirtualUsoMB: 5163,
    numeroThreads: 27,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [
      {
        id: 22956,
        nome: 'ServiceHub.IdentityHost.exe',
        nomeExecutavel:
          'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.IdentityHost.exe',
        memoriaUsoMB: 94,
        memoriaVirtualUsoMB: 2366090,
        numeroThreads: 22,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 86420,
    nome: 'ServiceHub.IdentityHost.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.IdentityHost.exe',
    memoriaUsoMB: 251,
    memoriaVirtualUsoMB: 2366102,
    numeroThreads: 26,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [
      {
        id: 71616,
        nome: 'Ana Castela - Olha Onde Eu Tô',
        nomeExecutavel:
          'C:\\Program Files\\WindowsApps\\SpotifyAB.SpotifyMusic_1.272.438.0_x64__zpdnekdrzrea0\\Spotify.exe',
        memoriaUsoMB: 101,
        memoriaVirtualUsoMB: 2200542,
        numeroThreads: 84,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 63120,
    nome: 'Spotify',
    nomeExecutavel:
      'C:\\Program Files\\WindowsApps\\SpotifyAB.SpotifyMusic_1.272.438.0_x64__zpdnekdrzrea0\\Spotify.exe',
    memoriaUsoMB: 224,
    memoriaVirtualUsoMB: 3589929,
    numeroThreads: 30,
    usoCpuModoUsuario: 0.08,
    usoCpuModoPrivilegiado: 0.05,
    usoCpuTotal: 0.14,
  },
  {
    subProcessos: [],
    id: 90040,
    nome: 'WhatsApp',
    nomeExecutavel:
      'C:\\Program Files\\WindowsApps\\5319275A.WhatsAppDesktop_2.2535.3.0_x64__cv1g1gvanyjgm\\WhatsApp.exe',
    memoriaUsoMB: 194,
    memoriaVirtualUsoMB: 6379,
    numeroThreads: 32,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [
      {
        id: 84344,
        nome: 'Visual Studio Code',
        nomeExecutavel: 'C:\\Users\\thiag\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
        memoriaUsoMB: 115,
        memoriaVirtualUsoMB: 3526104,
        numeroThreads: 27,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
      {
        id: 83752,
        nome: 'Visual Studio Code',
        nomeExecutavel: 'C:\\Users\\thiag\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
        memoriaUsoMB: 107,
        memoriaVirtualUsoMB: 3529375,
        numeroThreads: 24,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 88528,
    nome: 'Visual Studio Code',
    nomeExecutavel: 'C:\\Users\\thiag\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
    memoriaUsoMB: 169,
    memoriaVirtualUsoMB: 3522567,
    numeroThreads: 10,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [
      {
        id: 84460,
        nome: 'Swagger UI - Pessoal — Microsoft​ Edge',
        nomeExecutavel: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
        memoriaUsoMB: 141,
        memoriaVirtualUsoMB: 2267245,
        numeroThreads: 66,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
      {
        id: 86048,
        nome: 'Microsoft Edge',
        nomeExecutavel: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
        memoriaUsoMB: 104,
        memoriaVirtualUsoMB: 2201497,
        numeroThreads: 28,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
      {
        id: 85172,
        nome: 'Microsoft Edge',
        nomeExecutavel: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
        memoriaUsoMB: 94,
        memoriaVirtualUsoMB: 3416284,
        numeroThreads: 19,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
      {
        id: 84736,
        nome: 'Microsoft Edge',
        nomeExecutavel: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
        memoriaUsoMB: 78,
        memoriaVirtualUsoMB: 3416365,
        numeroThreads: 30,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 58892,
    nome: 'Microsoft Edge',
    nomeExecutavel: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    memoriaUsoMB: 165,
    memoriaVirtualUsoMB: 3423147,
    numeroThreads: 38,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [],
    id: 83636,
    nome: 'VBCSCompiler',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\Roslyn\\VBCSCompiler.exe',
    memoriaUsoMB: 151,
    memoriaVirtualUsoMB: 25069,
    numeroThreads: 26,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [],
    id: 95636,
    nome: 'ArgusCloud.API',
    nomeExecutavel:
      'C:\\Users\\thiag\\Documents\\projetosPessoais\\ArgusGeral\\Argus\\backend\\ArgusCloud\\ArgusCloud.API\\bin\\Debug\\net9.0\\ArgusCloud.API.exe',
    memoriaUsoMB: 139,
    memoriaVirtualUsoMB: 2366184,
    numeroThreads: 46,
    usoCpuModoUsuario: 0.03,
    usoCpuModoPrivilegiado: 0.27,
    usoCpuTotal: 0.3,
  },
  {
    subProcessos: [],
    id: 77524,
    nome: 'Windows Explorer',
    nomeExecutavel: 'C:\\WINDOWS\\Explorer.EXE',
    memoriaUsoMB: 130,
    memoriaVirtualUsoMB: 2102361,
    numeroThreads: 106,
    usoCpuModoUsuario: 0.03,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0.03,
  },
  {
    subProcessos: [
      {
        id: 96132,
        nome: 'ServiceHub.DataWarehouseHost.exe',
        nomeExecutavel:
          'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.DataWarehouseHost.exe',
        memoriaUsoMB: 123,
        memoriaVirtualUsoMB: 2366109,
        numeroThreads: 37,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 88056,
    nome: 'ServiceHub.DataWarehouseHost.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.DataWarehouseHost.exe',
    memoriaUsoMB: 128,
    memoriaVirtualUsoMB: 2366108,
    numeroThreads: 36,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [
      {
        id: 95760,
        nome: 'Microsoft Edge WebView2',
        nomeExecutavel:
          'C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\140.0.3485.54\\msedgewebview2.exe',
        memoriaUsoMB: 116,
        memoriaVirtualUsoMB: 2233903,
        numeroThreads: 62,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
      {
        id: 96024,
        nome: 'Microsoft Edge WebView2',
        nomeExecutavel:
          'C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\140.0.3485.54\\msedgewebview2.exe',
        memoriaUsoMB: 100,
        memoriaVirtualUsoMB: 2200684,
        numeroThreads: 22,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
      {
        id: 94204,
        nome: 'Microsoft Edge WebView2',
        nomeExecutavel:
          'C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\140.0.3485.54\\msedgewebview2.exe',
        memoriaUsoMB: 97,
        memoriaVirtualUsoMB: 2200648,
        numeroThreads: 20,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
      {
        id: 92348,
        nome: 'Microsoft Edge WebView2',
        nomeExecutavel:
          'C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\140.0.3485.54\\msedgewebview2.exe',
        memoriaUsoMB: 93,
        memoriaVirtualUsoMB: 3416348,
        numeroThreads: 27,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
      {
        id: 67256,
        nome: 'Microsoft Edge WebView2',
        nomeExecutavel:
          'C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\140.0.3485.54\\msedgewebview2.exe',
        memoriaUsoMB: 87,
        memoriaVirtualUsoMB: 3416283,
        numeroThreads: 19,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 72780,
    nome: 'Microsoft Edge WebView2',
    nomeExecutavel:
      'C:\\Program Files (x86)\\Microsoft\\EdgeWebView\\Application\\140.0.3485.54\\msedgewebview2.exe',
    memoriaUsoMB: 119,
    memoriaVirtualUsoMB: 2233938,
    numeroThreads: 62,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [
      {
        id: 72320,
        nome: 'ServiceHub.Host.dotnet.x64',
        nomeExecutavel:
          'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.Host.dotnet.x64.exe',
        memoriaUsoMB: 106,
        memoriaVirtualUsoMB: 2366227,
        numeroThreads: 21,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
      {
        id: 83172,
        nome: 'ServiceHub.Host.dotnet.x64',
        nomeExecutavel:
          'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.Host.dotnet.x64.exe',
        memoriaUsoMB: 88,
        memoriaVirtualUsoMB: 2366038,
        numeroThreads: 14,
        usoCpuModoUsuario: 0,
        usoCpuModoPrivilegiado: 0,
        usoCpuTotal: 0,
      },
    ],
    id: 92644,
    nome: 'ServiceHub.Host.dotnet.x64',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.Host.dotnet.x64.exe',
    memoriaUsoMB: 114,
    memoriaVirtualUsoMB: 2366229,
    numeroThreads: 22,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [],
    id: 91368,
    nome: 'ServiceHub.VSDetouredHost.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.VSDetouredHost.exe',
    memoriaUsoMB: 78,
    memoriaVirtualUsoMB: 2366086,
    numeroThreads: 16,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [],
    id: 73212,
    nome: 'MSBuild.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\amd64\\MSBuild.exe',
    memoriaUsoMB: 77,
    memoriaVirtualUsoMB: 4902,
    numeroThreads: 18,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
  {
    subProcessos: [],
    id: 93536,
    nome: 'Argus.Agent',
    nomeExecutavel:
      'C:\\Users\\thiag\\Documents\\projetosPessoais\\ArgusGeral\\Argus\\backend\\Argus.Agent\\bin\\Debug\\net8.0\\Argus.Agent.exe',
    memoriaUsoMB: 77,
    memoriaVirtualUsoMB: 2366047,
    numeroThreads: 29,
    usoCpuModoUsuario: 0.25,
    usoCpuModoPrivilegiado: 0.29,
    usoCpuTotal: 0.55,
  },
  {
    subProcessos: [],
    id: 90688,
    nome: 'ServiceHub.ThreadedWaitDialog.exe',
    nomeExecutavel:
      'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\ServiceHub\\Hosts\\ServiceHub.Host.dotnet.x64\\ServiceHub.ThreadedWaitDialog.exe',
    memoriaUsoMB: 74,
    memoriaVirtualUsoMB: 2366536,
    numeroThreads: 81,
    usoCpuModoUsuario: 0,
    usoCpuModoPrivilegiado: 0,
    usoCpuTotal: 0,
  },
]
